### ISSUE TITLE
Stats page causes server error

### ISSUE THREAD

**Issue by TigerWolf** [Firstyear/beerclub#11]

**Comment by Firstyear** [comment]
NEEDINFO

**Comment by TigerWolf** [comment]
<img width="953" alt="screen shot 2016-04-29 at 5 53 01 pm" src="https://cloud.githubusercontent.com/assets/501033/14911245/465c78d4-0e33-11e6-91f4-6a516e45830d.png">

**Comment by TigerWolf** [comment]
Fixed.
